# Generated by Django 6.1 on 2026-09-24 18:05

import bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('packages', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default=bookings.models.generate_booking_code, editable=False, max_length=20, unique=True)),
                ('trip_type', models.CharField(choices=[('oneway', 'Outstation One-Way'), ('roundtrip', 'Outstation Round-Trip'), ('local', 'Local Ride (> 20 km)')], default='oneway', max_length=20)),
                ('pickup_address', models.CharField(max_length=255)),
                ('destination_address', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('return_date', models.DateField(blank=True, help_text='Required for Round-Trip', null=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes_and_tolls', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_fixed_price', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI / QR Payment'), ('card', 'Credit / Debit Card'), ('cash', 'Cash to Driver'), ('package', 'Instant Cab Package Ride')], default='upi', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed & Scheduled'), ('ongoing', 'Ride In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cab_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='pricing.cabtype')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='drivers.driver')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='pricing.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('user_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_bookings', to='packages.userpackage')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
