# Generated by Django 6.1 on 2026-09-24 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('luxury', 'Luxury'), ('tempo', 'Tempo Traveller')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=4)),
                ('luggage_capacity', models.IntegerField(default=2, help_text='Number of large bags')),
                ('image', models.FileField(blank=True, null=True, upload_to='cab_types/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cab Type',
                'verbose_name_plural': 'Cab Types',
            },
        ),
        migrations.CreateModel(
            name='LocalRideSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance', models.DecimalField(decimal_places=2, help_text='Minimum distance (km)', max_digits=8)),
                ('max_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum distance (km), leave blank for unlimited', max_digits=8, null=True)),
                ('rate_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('cab_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_slabs', to='pricing.cabtype')),
            ],
            options={
                'verbose_name': 'Local Ride Slab',
                'verbose_name_plural': 'Local Ride Slabs',
                'ordering': ['cab_type', 'min_distance'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['pickup', 'destination'],
                'unique_together': {('pickup', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='FixedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cab_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_prices', to='pricing.cabtype')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_prices', to='pricing.route')),
            ],
            options={
                'verbose_name': 'Fixed Price',
                'verbose_name_plural': 'Fixed Prices',
                'unique_together': {('route', 'cab_type')},
            },
        ),
    ]
