# Generated by Django 6.1 on 2026-09-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
